apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-stats
  namespace: goblncr-test
  labels:
    app: express-stats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-stats
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: express-stats
    spec:
      containers:
        - name: express-stats
          image: express-stats
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "150M"
            limits:
              cpu: "200m"
              memory: "300M"
          envFrom:
            - configMapRef:
                name: express-stats

          env:
            - name: K8S_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always
