apiVersion: v1
kind: Service
metadata:
  name: express-stats-svc
  namespace: goblncr-test
  labels:
    app: express-stats-svc
spec:
  type: LoadBalancer
  ports:
    - name: "web-port"
      port: 8083
      targetPort: 8083
  selector:
    app: express-stats
