apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: goblncr-test
data:
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tokenMirEgal
  DOCKER_INFLUXDB_INIT_BUCKET: request_stats
  DOCKER_INFLUXDB_INIT_MODE: setup
  DOCKER_INFLUXDB_INIT_ORG: goblncr-test
  DOCKER_INFLUXDB_INIT_PASSWORD: admin
  DOCKER_INFLUXDB_INIT_USERNAME: admin
  
  pods_distribution_dashboard.json: |-
    [
        {
            "apiVersion": "influxdata.com/v2alpha1",
            "kind": "Label",
            "metadata": {
                "name": "adventuring-mcnulty-c24001"
            },
            "spec": {
                "color": "#5c10a0",
                "name": "pods"
            }
        },
        {
            "apiVersion": "influxdata.com/v2alpha1",
            "kind": "Dashboard",
            "metadata": {
                "name": "naughty-matsumoto-024001"
            },
            "spec": {
                "associations": [
                    {
                        "kind": "Label",
                        "name": "adventuring-mcnulty-c24001"
                    }
                ],
                "charts": [
                    {
                        "axes": [
                            {
                                "base": "10",
                                "name": "x",
                                "scale": "linear"
                            },
                            {
                                "base": "10",
                                "name": "y",
                                "scale": "linear"
                            }
                        ],
                        "colorizeRows": true,
                        "colors": [
                            {
                                "id": "_9TuO_dg_46ilqupzycYC",
                                "name": "Nineteen Eighty Four",
                                "type": "scale",
                                "hex": "#31C0F6"
                            },
                            {
                                "id": "p_7AWM29SgxGddEffvocz",
                                "name": "Nineteen Eighty Four",
                                "type": "scale",
                                "hex": "#A500A5"
                            },
                            {
                                "id": "9WF-5lDyWX6i9RsW6d_R_",
                                "name": "Nineteen Eighty Four",
                                "type": "scale",
                                "hex": "#FF7E27"
                            }
                        ],
                        "geom": "line",
                        "height": 5,
                        "hoverDimension": "auto",
                        "kind": "Xy",
                        "legendColorizeRows": true,
                        "legendOpacity": 1,
                        "legendOrientationThreshold": 100000000,
                        "name": "Name this Cell",
                        "opacity": 1,
                        "orientationThreshold": 100000000,
                        "position": "overlaid",
                        "queries": [
                            {
                                "query": "from(bucket: \"request_stats\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"request\" and r._field == \"status_code\")\n  // Grouping by your main metric splits the visualization into individual lines per pod\n  |> group(columns: [\"pod_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)\n  |> yield(name: \"count\")"
                            }
                        ],
                        "staticLegend": {
                            "colorizeRows": true,
                            "opacity": 1,
                            "orientationThreshold": 100000000,
                            "widthRatio": 1
                        },
                        "width": 12,
                        "widthRatio": 1,
                        "xCol": "_time",
                        "yCol": "_value"
                    }
                ],
                "name": "pods distribution"
            }
        }
    ]