apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb-data
  name: influxdb-data
  namespace: goblncr-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
